# Generated by Django 5.0.4 on 2024-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msedata",
            old_name="businessRegistered",
            new_name="isbusinessRegistered",
        ),
        migrations.RenameField(
            model_name="msedata",
            old_name="capacityTraining",
            new_name="participatedintradefair",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="chama",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="chamaOperation",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="diasability",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="marketing",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="membershipPosition",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="nameOfChama",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="participated",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="subCounty",
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="wubcounty",
        ),
        migrations.AddField(
            model_name="msedata",
            name="capacityTrainingParticipation",
            field=models.CharField(
                choices=[
                    ("Self-sponsored", "Self-sponsored"),
                    ("Sponsored", "Sponsored"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="msedata",
            name="marketingProducts",
            field=models.CharField(
                choices=[
                    ("Virtual", "Virtual"),
                    ("Physical", "Physical"),
                    ("Both", "Both"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="msedata",
            name="otherChallenges",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="msedata",
            name="otherExpectations",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="msedata",
            name="other_gender",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="msedata",
            name="othergroupActivites",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="businessSector",
            field=models.CharField(
                choices=[
                    ("Retail", "Retail"),
                    ("Wholesale", "Wholesale"),
                    ("Service", "Service"),
                    ("Juakali/cottage", "Juakali/cottage"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="challenges",
            field=models.TextField(
                choices=[
                    (
                        "Inadequate access to affordable capital",
                        "Inadequate access to affordable capital",
                    ),
                    ("Limited market access", "Limited market access"),
                    (
                        "Inadequate business/entrepreneur skills",
                        "Inadequate business/entrepreur skills",
                    ),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="expectations",
            field=models.CharField(
                choices=[
                    ("Increased working capital", "Increase working capital"),
                    ("Access to more customers", "Access to more customers"),
                    (
                        "Enhanced business/ entrepreneurial skills",
                        "Enhanced business/  entrepreneurial skills",
                    ),
                    (" Increased business income ", "Increased business income"),
                    (" More employment opportunities", "More employment opportunities"),
                    (" Better livelihood", "Better livelihood"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="explainWhy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="groupActivities",
            field=models.CharField(
                choices=[
                    ("Car Wash", "Car Wash"),
                    ("Metal works/ Furniture", "Metal works/ Furniture"),
                    ("Fish mongering", "Fish mongering"),
                    ("Health Care", "Health Care"),
                    ("Waste recyclers/ CBOs", "Waste recyclers/ CBOs"),
                    ("Tailoring/ Basket Making", "Tailoring/ Basket Making"),
                    ("Hawking", "Hawking"),
                    ("Juice making", "Juice making"),
                    ("Salon/ nail salon", "Salon/ nail salon"),
                    ("Chicken farming", "Chicken farming"),
                    ("Mechanics", "Mechanics"),
                    ("Shoe shiners", "Shoe shiners"),
                    ("Catering", "Catering"),
                    ("Boda Boda", "Boda Boda"),
                    ("Leather Shoe makers", "Leather Shoe makers"),
                    ("Cleaning services", "Cleaning services"),
                    ("Arts and Entertainment", "Arts and Entertainment"),
                    ("Day care", "Day care"),
                    ("Masonry", "Masonry"),
                    ("Jua Kali", "Jua Kali"),
                    ("General Merchandise", "General Merchandise"),
                    ("Other", "Other"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="groupConsitution",
            field=models.FileField(
                upload_to="",
                verbose_name=models.FileField(
                    blank=True, null=True, upload_to="GroupConstitution/"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="groupRegCert",
            field=models.FileField(
                upload_to="",
                verbose_name=models.FileField(
                    blank=True, null=True, upload_to="GroupCetificate/"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="lengthofOPerations",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="listOfGroupmembers",
            field=models.FileField(
                upload_to="",
                verbose_name=models.FileField(
                    blank=True, null=True, upload_to="GroupMembers/"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="numbofEmployees",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="registrationCertificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="sourceofCapital",
            field=models.CharField(
                choices=[
                    ("Own Savings", "Own Savings"),
                    ("Family/Friend support", "Family/Friend support"),
                    ("Chama", "Chama"),
                    ("Loan", "Loan"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="targetMarket",
            field=models.CharField(
                choices=[("Local", "Local"), ("International", "International")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="tradefairParticipation",
            field=models.CharField(
                choices=[
                    ("Self-sponsored", "Self-sponsored"),
                    ("Sponsored", "Sponsored"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="ward",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="msedata",
            name="subcounty",
            field=models.CharField(
                choices=[
                    (" Dagoretti South", " Dagoretti South"),
                    (" Dagoretti North", " Dagoretti North"),
                    (" Embakasi East", " Embakasi East"),
                    (" Embakasi Central", " Embakasi Central"),
                    (" Embakasi North", " Embakasi North"),
                    ("Embakasi West", "Embakasi West"),
                    ("Embakasi South", "Embakasi South"),
                    (" Kamukunji", " Kamukunji"),
                    (" Kasarani", " Kasarani"),
                    (" Kibra", " Kibra"),
                    (" Langata", " Langata"),
                    ("Makadara", "Makadara"),
                    ("  Mathare", "  Mathare"),
                    (" Starehe", " Starehe"),
                    (" Westlands", " Westlands"),
                    ("Roysambu", " Roysambu"),
                    ("Ruaraka", "Ruaraka"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
