# Generated by Django 5.0.4 on 2024-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MSEs_App",
            "0002_rename_businessregistered_msedata_isbusinessregistered_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="groupConsitution",
            field=models.FileField(
                blank=True, null=True, upload_to="groupconstitution/"
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="groupRegCert",
            field=models.FileField(
                blank=True, null=True, upload_to="groupCertificate/"
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="listOfGroupmembers",
            field=models.FileField(blank=True, null=True, upload_to="groupmembers/"),
        ),
    ]
