# Generated by Django 5.0.4 on 2024-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0003_alter_msedata_groupconsitution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="diasabilityStatus",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="nationalIDPhoto",
            field=models.FileField(upload_to="nationalid/"),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="passportPhoto",
            field=models.FileField(upload_to="passport/"),
        ),
    ]
