# Generated by Django 5.0.4 on 2024-04-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0004_alter_msedata_diasabilitystatus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msedata",
            old_name="lengthofOPerations",
            new_name="lengthofOperations",
        ),
    ]
