# Generated by Django 5.0.4 on 2024-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0005_rename_lengthofoperations_msedata_lengthofoperations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="lengthofOperations",
            field=models.CharField(
                choices=[
                    ("0-6 months", "0-6 months"),
                    ("6-12 months", "6-12 months"),
                    ("1-2 years", "1-2 years"),
                    ("2-3 years", "2-3 years"),
                    ("3 Years and above", "3 years and above"),
                ],
                max_length=40,
            ),
        ),
    ]
