# Generated by Django 5.0.4 on 2024-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0006_alter_msedata_lengthofoperations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="groupConsitution",
            field=models.FileField(
                blank=True, null=True, upload_to="media/groupconstitution/"
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="groupRegCert",
            field=models.FileField(
                blank=True, null=True, upload_to="media/groupCertificate/"
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="listOfGroupmembers",
            field=models.FileField(
                blank=True, null=True, upload_to="media/groupmembers/"
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="nationalIDPhoto",
            field=models.FileField(upload_to="media/nationalid/"),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="otherChallenges",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="otherExpectations",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="othergroupActivites",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="passportPhoto",
            field=models.FileField(upload_to="media/passport/"),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="registrationCertificate",
            field=models.FileField(
                blank=True, null=True, upload_to="media/certificates/"
            ),
        ),
    ]
