# Generated by Django 5.0.4 on 2024-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0007_alter_msedata_groupconsitution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="registrationCertificate",
            field=models.FileField(
                blank=True, null=True, upload_to="media/businesscertificates/"
            ),
        ),
    ]
