# Generated by Django 5.0.4 on 2024-04-09 12:06

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0012_alter_msedata_groupactivities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="groupActivities",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.AddField(
            model_name="msedata",
            name="groupActivities",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Car Wash", "Car Wash"),
                    ("Metal works/ Furniture", "Metal works/ Furniture"),
                    ("Fish mongering", "Fish mongering"),
                    ("Health Care", "Health Care"),
                    ("Waste recyclers/ CBOs", "Waste recyclers/ CBOs"),
                    ("Tailoring/ Basket Making", "Tailoring/ Basket Making"),
                    ("Hawking", "Hawking"),
                    ("Juice making", "Juice making"),
                    ("Salon/ nail salon", "Salon/ nail salon"),
                    ("Chicken farming", "Chicken farming"),
                    ("Mechanics", "Mechanics"),
                    ("Shoe shiners", "Shoe shiners"),
                    ("Catering", "Catering"),
                    ("Boda Boda", "Boda Boda"),
                    ("Leather Shoe makers", "Leather Shoe makers"),
                    ("Cleaning services", "Cleaning services"),
                    ("Arts and Entertainment", "Arts and Entertainment"),
                    ("Day care", "Day care"),
                    ("Masonry", "Masonry"),
                    ("Jua Kali", "Jua Kali"),
                    ("General Merchandise", "General Merchandise"),
                    ("Other", "Other"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
