# Generated by Django 5.0.4 on 2024-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0013_remove_msedata_groupactivities_delete_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="msedata",
            name="groupActivities",
        ),
        migrations.AddField(
            model_name="msedata",
            name="groupActivities",
            field=models.ManyToManyField(blank=True, null=True, to="MSEs_App.activity"),
        ),
    ]
