# Generated by Django 5.0.4 on 2024-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0014_activity_remove_msedata_groupactivities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="isChamaRegistered",
        ),
        migrations.AddField(
            model_name="msedata",
            name="isGroupRegistered",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="awareofProgram",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capacityBuildingTraining",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capitalisAdequate",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isbusinessRegistered",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="participatedintradefair",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=25
            ),
        ),
    ]
