# Generated by Django 5.0.4 on 2024-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0015_remove_msedata_ischamaregistered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="groupActivities",
        ),
        migrations.AddField(
            model_name="msedata",
            name="groupActivities",
            field=models.JSONField(default=list),
        ),
    ]
