# Generated by Django 5.0.4 on 2024-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0017_alter_msedata_groupactivities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="subcounty",
            field=models.CharField(
                choices=[
                    ("Dagoretti South", "Dagoretti South"),
                    ("Dagoretti North", "Dagoretti North"),
                    ("Embakasi East", "Embakasi East"),
                    ("Embakasi Central", "Embakasi Central"),
                    ("Embakasi North", "Embakasi North"),
                    ("Embakasi West", "Embakasi West"),
                    ("Embakasi South", "Embakasi South"),
                    ("Kamukunji", "Kamukunji"),
                    ("Kasarani", "Kasarani"),
                    ("Kibra", "Kibra"),
                    ("Langata", "Langata"),
                    ("Makadara", "Makadara"),
                    ("Mathare", "Mathare"),
                    ("Starehe", "Starehe"),
                    ("Westlands", "Westlands"),
                    ("Roysambu", "Roysambu"),
                    ("Ruaraka", "Ruaraka"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
