# Generated by Django 5.0.4 on 2024-04-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0018_alter_msedata_subcounty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msedata",
            old_name="diasabilityStatus",
            new_name="disabilityStatus",
        ),
    ]
