# Generated by Django 5.0.4 on 2024-04-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0019_rename_diasabilitystatus_msedata_disabilitystatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
