# Generated by Django 5.0.4 on 2024-04-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0021_alter_msedata_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="year_registered",
        ),
    ]
