# Generated by Django 5.0.4 on 2024-04-10 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0023_msedata_year_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="year_registered",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
    ]
