# Generated by Django 5.0.4 on 2024-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0025_remove_msedata_id_alter_msedata_identificationnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="capacityTrainingParticipation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Self-sponsored", "Self-sponsored"),
                    ("Sponsored", "Sponsored"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isGroupRegistered",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="numbofEmployees",
            field=models.CharField(
                choices=[("1-10", "1-10"), ("11-50 ", "11-50")], max_length=25
            ),
        ),
    ]
