# Generated by Django 5.0.4 on 2024-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0026_alter_msedata_capacitytrainingparticipation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="expectations",
        ),
        migrations.AddField(
            model_name="msedata",
            name="expectationss",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
