# Generated by Django 5.0.4 on 2024-04-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0027_remove_msedata_expectations_msedata_expectationss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msedata",
            old_name="expectationss",
            new_name="expectations",
        ),
    ]
