# Generated by Django 5.0.4 on 2024-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0028_rename_expectationss_msedata_expectations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="awareofProgram",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capacityBuildingTraining",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capitalisAdequate",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="disabilityStatus",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isGroupRegistered",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isbusinessRegistered",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="participatedintradefair",
            field=models.BooleanField(default=True),
        ),
    ]
