# Generated by Django 5.0.4 on 2024-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0029_alter_msedata_awareofprogram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="awareofProgram",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capacityBuildingTraining",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capitalisAdequate",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="disabilityStatus",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isGroupRegistered",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="isbusinessRegistered",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="participatedintradefair",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=False,
                max_length=25,
                null=True,
            ),
        ),
    ]
