# Generated by Django 5.0.4 on 2024-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0030_alter_msedata_awareofprogram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="businessSector",
            field=models.CharField(
                choices=[
                    ("retail", "retail"),
                    ("wholesale", "wholesale"),
                    ("service", "service"),
                    ("juakali", "juakali"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="capacityTrainingParticipation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self-sponsored", "self-sponsored"),
                    ("sponsored", "sponsored"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="challenges",
            field=models.TextField(
                choices=[
                    (
                        "Inadequate access to affordable capital",
                        "Inadequate access to affordable capital",
                    ),
                    ("Limited market access", "Limited market access"),
                    (
                        "Inadequate business/ entrepreneur skills",
                        "Inadequate business/ entrepreur skills",
                    ),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("other", "other")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="marketingProducts",
            field=models.CharField(
                choices=[
                    ("virtual", "virtual"),
                    ("physical", "physical"),
                    ("both", "both"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="targetMarket",
            field=models.CharField(
                choices=[("local", "local"), ("international", "international")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="tradefairParticipation",
            field=models.CharField(
                choices=[
                    ("self-sponsored", "self-sponsored"),
                    ("sponsored", "sponsored"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
