# Generated by Django 5.0.4 on 2024-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0031_alter_msedata_businesssector_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="msedata",
        #     name="id",
        #     field=models.IntegerField(default=0, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name="msedata",
        #     name="identificationNumber",
        #     field=models.IntegerField(null=True),
        # ),
        migrations.AlterField(
            model_name="msedata",
            name="phoneNumber",
            field=models.CharField(max_length=20),
        ),
    ]
