# Generated by Django 5.0.4 on 2024-04-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0033_alter_msedata_id"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="msedata",
        #     name="identificationNumber",
        # ),
    ]
