# Generated by Django 5.0.4 on 2024-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0034_remove_msedata_identificationnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msedata",
            name="identificationNumber",
        ),
        
        migrations.AddField(
            model_name="msedata",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
               
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
