# Generated by Django 5.0.4 on 2024-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0035_remove_msedata_identificationnumber_msedata_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="msedata",
            name="identificationNumber",
            field=models.IntegerField(null=True),
        ),
    ]
