# Generated by Django 5.0.4 on 2024-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSEs_App", "0036_msedata_identificationnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msedata",
            name="challenges",
            field=models.TextField(
                choices=[
                    (
                        "Inadequate access to affordable capital",
                        "Inadequate access to affordable capital",
                    ),
                    ("Limited market access", "Limited market access"),
                    (
                        "Inadequate business/ entrepreneur skills",
                        "Inadequate business/ entrepreneur skills",
                    ),
                    ("other", "other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="lengthofOperations",
            field=models.CharField(
                choices=[
                    ("0-6 Months", "0-6 Months"),
                    ("1-2 Years", "1-2 Years"),
                    ("2-3 Years", "2-3 Years"),
                    ("3 Years and Above", "3 Years and Above"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="msedata",
            name="numbofEmployees",
            field=models.CharField(
                choices=[("1-10", "1-10"), ("11-50", "11-50")], max_length=25
            ),
        ),
    ]
